package com.app.xit.userprofile

data class DriverHistoryModel(val id1: String?, val order_number: String?,
                              val user_id: String?, val p_company_name: String?,
                              val p_contact_name: String?, val p_address: String?,
                              val p_email: String?, val p_phone: String?,
                              val p_comment: String?, val p_photourl: String?,
                              val p_unit_no: String?, val p_hsn_no: String?,
                              val p_route: String?, val p_country: String?,
                              val p_city: String?, val p_state: String?,
                              val p_zipcode: String?, val d_company_name: String?,
                              val d_contact_name: String?, val d_address: String?,
                              val d_email: String?, val d_phone: String?,
                              val d_comment: String?, val d_photourl: String?,
                              val d_unit_no: String?, val d_hsn_no: String?,
                              val d_route: String?, val d_country: String?,
                              val d_city: String?, val d_state: String?,
                              val d_zipcode: String?, val length: String?,
                              val breath: String?, val height: String?,
                              val no_of_pcs: String?, val weight: String?,
                              val vechile: String?, val value: String?,
                              val service: String?, val miles: String?,
                              val times_in_min: String?, val total_amount: String?,
                              val additional_charge: String?, val vechile_charge: String?,
                              val payment_mode: String?, val date_and_time: String?,
                              val order_status: String?, val status: String?,
                              val reference_no: String?, val end_user: String?,
                              val emailer_name: String?, val d_emailer_name: String?,
                              val notification: String?, val notification_name: String?,
                              val d_notification_name: String?, val p_business: String?,
                              val d_business: String?, val assign_id: String?,
                              val driver_id: String?, val order_id: String?,
                              val assigned_date: String?, val order_complete_status: String?)
